BNP.Web/Models/MovimentoManualGridItemViewModel.cs
using System;

namespace BNP.Web.Models
{
    public class MovimentoManualGridItemViewModel
    {
        public int NumeroLancamento { get; set; }
        public string CodigoProduto { get; set; }
        public string CodigoCosif { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public string Usuario { get; set; }
        public DateTime DataMovimento { get; set; }
    }
}

BNP.Web/Models/MovimentoManualViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BNP.Web.Models
{
    public class MovimentoManualViewModel
    {
        public int Mes { get; set; }
        public int Ano { get; set; }
        public string CodigoProduto { get; set; }
        public string CodigoCosif { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }

        public IEnumerable<SelectListItem> Produtos { get; set; }
        public IEnumerable<SelectListItem> Cosifs { get; set; }

        public List<MovimentoManualGridItemViewModel> Grid { get; set; }
    }
}

BNP.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BNP.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BNP.Web/Controllers/MovimentoManualController.cs
using BNP.Application.DTOs;
using BNP.Application.Interfaces;
using BNP.Domain.Interfaces;
using BNP.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BNP.Web.Controllers
{
    public class MovimentoManualController : Controller
    {
        private readonly IMovimentoManualAppService _app;
        private readonly IProdutoRepository _prodRep;
        private readonly IProdutoCosifRepository _cosifRep;

        public MovimentoManualController(
            IMovimentoManualAppService app,
            IProdutoRepository prodRep,
            IProdutoCosifRepository cosifRep)
        {
            _app = app; _prodRep = prodRep; _cosifRep = cosifRep;
        }

        [HttpGet]
        public ActionResult Index(int mes = 1, int ano = 2025)
        {
            var gridData = _app.Listar(mes, ano)
            .Select(x => new MovimentoManualGridItemViewModel
            {
                NumeroLancamento = (int)x.GetType().GetProperty("NumeroLancamento").GetValue(x),
                CodigoProduto = (string)x.GetType().GetProperty("CodigoProduto").GetValue(x),
                CodigoCosif = (string)x.GetType().GetProperty("CodigoCosif").GetValue(x),
                Descricao = (string)x.GetType().GetProperty("Descricao").GetValue(x),
                Valor = (decimal)x.GetType().GetProperty("Valor").GetValue(x),
                Usuario = (string)x.GetType().GetProperty("Usuario").GetValue(x),
                DataMovimento = (DateTime)x.GetType().GetProperty("DataMovimento").GetValue(x),
            }).ToList();

            var vm = new MovimentoManualViewModel
            {
                Mes = mes,
                Ano = ano,
                Grid = gridData,
                Produtos = _prodRep.ObterTodos().Select(p => new SelectListItem
                {
                    Value = p.Codigo,
                    Text = p.Descricao
                })
            };

            vm.Cosifs = Enumerable.Empty<SelectListItem>();
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MovimentoManualViewModel vm)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index", new { mes = vm.Mes, ano = vm.Ano });

            _app.Criar(new MovimentoManualDto
            {
                Mes = vm.Mes,
                Ano = vm.Ano,
                CodigoProduto = vm.CodigoProduto,
                CodigoCosif = vm.CodigoCosif,
                Descricao = vm.Descricao,
                Valor = vm.Valor
            });

            return RedirectToAction("Index", new { mes = vm.Mes, ano = vm.Ano });
        }

        [HttpGet]
        public JsonResult CosifsPorProduto(string codProduto)
        {
            var data = _cosifRep.ObterPorProduto(codProduto)
                        .Select(c => new { value = c.CodigoCosif, text = c.CodigoCosif + " (" + c.CodigoClassificacao + ")" });
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

BNP.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

BNP.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

BNP.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

BNP.Web/Views/MovimentoManual/Index.cshtml
@model BNP.Web.Models.MovimentoManualViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Movimentos Manuais";
}

<h2>Movimentos Manuais (@Model.Mes/@Model.Ano)</h2>

@using (Html.BeginForm("Create", "MovimentoManual", FormMethod.Post, new { id = "formMovimento" }))
{
    @Html.AntiForgeryToken()

    <fieldset id="formCampos" disabled>
        <div class="form-row">
            <div class="form-group col-md-6">
                @Html.LabelFor(m => m.Mes)
                @Html.TextBoxFor(m => m.Mes, new { @class = "form-control", type = "number" })
            </div>
            <div class="form-group col-md-6">
                @Html.LabelFor(m => m.Ano)
                @Html.TextBoxFor(m => m.Ano, new { @class = "form-control", type = "number" })
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                @Html.Label("Produto")
                @Html.DropDownListFor(m => m.CodigoProduto, Model.Produtos, "-- selecione --", new { @class = "form-control", id = "ddlProduto" })
            </div>
            <div class="form-group col-md-6">
                @Html.Label("Cosif")
                @Html.DropDownList("CodigoCosif", Enumerable.Empty<SelectListItem>(), "-- selecione --", new { @class = "form-control", id = "ddlCosif" })
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Valor)
                @Html.TextBoxFor(m => m.Valor, new { @class = "form-control", type = "number", step = "0.01" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Descricao)
            @Html.TextBoxFor(m => m.Descricao, new { @class = "form-control" })
        </div>
    </fieldset>

    <div class="form-group mt-3">
        <button type="button" id="btnLimpar" class="btn btn-warning d-none">Limpar</button>
        <button type="button" id="btnNovo" class="btn btn-primary">Novo</button>
        <button type="submit" id="btnSalvar" class="btn btn-success d-none">Incluir</button>
        <button type="button" id="btnCancelar" class="btn btn-secondary d-none">Cancelar</button>
    </div>
}

<hr />

@if (Model.Grid != null)
{
    <table class="table table-bordered table-striped mt-4">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Produto</th>
                <th>COSIF</th>
                <th>Descrição</th>
                <th>Valor</th>
                <th>Data</th>
                <th>Usuário</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Grid)
            {
                <tr>
                    <td>@item.NumeroLancamento</td>
                    <td>@item.CodigoProduto</td>
                    <td>@item.CodigoCosif</td>
                    <td>@item.Descricao</td>
                    <td>@item.Valor</td>
                    <td>@item.DataMovimento</td>
                    <td>@item.Usuario</td>
                </tr>
            }
        </tbody>
    </table>
}

@section scripts {
    <script>
        $(function () {
            $('#btnNovo').click(function () {
                $('#formCampos').removeAttr('disabled');
                $('#btnSalvar, #btnCancelar, #btnLimpar').removeClass('d-none');
                $('#btnNovo').addClass('d-none');
            });

            $('#btnCancelar').click(function () {
                $('#formMovimento')[0].reset();
                $('#formCampos').attr('disabled', 'disabled');
                $('#btnSalvar, #btnCancelar, #btnLimpar').addClass('d-none');
                $('#btnNovo').removeClass('d-none');
                $('#ddlCosif').empty().append($('<option>').val('').text('-- selecione --'));
            });

            $('#btnLimpar').click(function () {
                $('#formMovimento')[0].reset();
                $('#ddlCosif').empty().append($('<option>').val('').text('-- selecione --'));
            });

           $('#ddlProduto').change(function () {
                var codProduto = $(this).val();
                console.log("Produto selecionado: " + codProduto);

                var $cosif = $('#ddlCosif');
                $cosif.empty().append($('<option>').val('').text('-- selecione --'));

                if (codProduto) {
                    var url = '@Url.Action("CosifsPorProduto", "MovimentoManual")';
                    console.log("Chamando endpoint: " + url);

                    $.getJSON(url, { codProduto: codProduto }, function (data) {
                        console.log("Resposta do endpoint:", data);
                        $.each(data, function (_, item) {
                            $cosif.append($('<option>').val(item.value).text(item.text));
                        });
                    });
                }
            });
        });
    </script>
}

BNP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Movimentos Manuais</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-4">
        <div class="container">
            @Html.ActionLink("Movimentos", "Index", "MovimentoManual", null, new { @class = "navbar-brand" })

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Início", "Index", "MovimentoManual", null, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-muted small">
            <p>&copy; @DateTime.Now.Year - Sistema de Movimentos Manuais</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>